name: Build

env:
  APP_VERSION: 0.0.4

on: [push]

jobs:
  build_linux:
    name: Build Linux version
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      - name: Checkout Sources
        uses: actions/checkout@master

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.1
          target: desktop

      - name: Run QMake
        shell: bash
        run: |
          cd src
          qmake starc.pro

      - name: Build
        shell: bash
        run: |
          cd src
          make -j$(nproc)

      - name: Make deb-package
        shell: bash
        run: |
          cd build/linux
          ./make-deb_amd64.sh ${{env.APP_VERSION}}

      - name: Collect artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux packages
          path: build/linux/starc-setup-${{env.APP_VERSION}}_amd64.deb

  build_windows:
    name: Build Windows version
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout Sources
        uses: actions/checkout@master

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.15.1
          arch: win64_msvc2019_64
          target: desktop
          
      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Run QMake
        shell: bash
        run: |
          cd src
          qmake starc.pro CONFIG+=release

      - name: Build
        shell: bash
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd src
          nmake
          
      - name: Make installer
        uses: joncloud/makensis-action@v3.4
        with:
          arguments: "/V3"
          script-file: "build/windows/starc64.nsi"
#           additional-plugin-paths: ${{ github.workspace }}/NSIS_Plugins/Plugins/

      - name: Collect artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux packages
          path: build/windows/starc-setup_64.exe
      
